[tool.poetry]
name = "caixa-v2"
version = "0.1.0"
description = ""
authors = ["Thiago"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
qrcode-terminal = "^0.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
